#!/bin/sh

grep -E "^aboot_platform=x86_64-arista_7800.*_(lc|sup)$" /host/machine.conf >/dev/null 2>&1 || exit 0

if [ ! -f /etc/sonic/arista.config ]; then
    cat >/etc/sonic/arista.config <<EOF
api_linecard_reboot_graceful: true
xcvr_lpmode_out: true
EOF
fi
